---
- name: Set up firewall
  service:
    name: firewalld
    state: stopped
    enabled: no


- name: Install git, curl, wget, vim, epel-release, remi-repo
  yum: 
    name: "{{ item }}" 
    state: installed
  with_items:
     - git
     - curl
     - wget
     - vim
     - epel-release
     - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm