---
- name: Install php
  yum: 
    name: "{{ item }}" 
    enablerepo: remi,remi-php70 
    state: present
  with_items:
    - php
    - php-mbstring
    - php-devel
    - php-opcache
    - php-soap
    - php-pdo
    - php-mcrypt
    - php-pecl-xdebug
    - php-xml
    - php-mysql
    - php-gd
  notify:
  - restart httpd
