---
- name: MySql packages are installed
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python

- name: Start the MySQL service
  service: 
    name: mariadb
    state: started 
    enabled: true